# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.setting = QtWidgets.QGroupBox(self.centralwidget)
        self.setting.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setting.sizePolicy().hasHeightForWidth())
        self.setting.setSizePolicy(sizePolicy)
        self.setting.setObjectName("setting")
        self.gridLayout = QtWidgets.QGridLayout(self.setting)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.setting)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.device_combobox = QtWidgets.QComboBox(self.setting)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.device_combobox.sizePolicy().hasHeightForWidth())
        self.device_combobox.setSizePolicy(sizePolicy)
        self.device_combobox.setObjectName("device_combobox")
        self.gridLayout.addWidget(self.device_combobox, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.setting)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.baudrate_combobox = QtWidgets.QComboBox(self.setting)
        self.baudrate_combobox.setObjectName("baudrate_combobox")
        self.baudrate_combobox.addItem("")
        self.baudrate_combobox.addItem("")
        self.baudrate_combobox.addItem("")
        self.gridLayout.addWidget(self.baudrate_combobox, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.setting)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.parity_combobox = QtWidgets.QComboBox(self.setting)
        self.parity_combobox.setObjectName("parity_combobox")
        self.parity_combobox.addItem("")
        self.parity_combobox.addItem("")
        self.parity_combobox.addItem("")
        self.parity_combobox.addItem("")
        self.parity_combobox.addItem("")
        self.gridLayout.addWidget(self.parity_combobox, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.setting)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.flowcontrol_combobox = QtWidgets.QComboBox(self.setting)
        self.flowcontrol_combobox.setObjectName("flowcontrol_combobox")
        self.flowcontrol_combobox.addItem("")
        self.flowcontrol_combobox.addItem("")
        self.gridLayout.addWidget(self.flowcontrol_combobox, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.setting)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.databits_combobox = QtWidgets.QComboBox(self.setting)
        self.databits_combobox.setEditable(False)
        self.databits_combobox.setObjectName("databits_combobox")
        self.databits_combobox.addItem("")
        self.databits_combobox.addItem("")
        self.databits_combobox.addItem("")
        self.databits_combobox.addItem("")
        self.gridLayout.addWidget(self.databits_combobox, 4, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.setting)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.stopbits_combobox = QtWidgets.QComboBox(self.setting)
        self.stopbits_combobox.setObjectName("stopbits_combobox")
        self.stopbits_combobox.addItem("")
        self.stopbits_combobox.addItem("")
        self.gridLayout.addWidget(self.stopbits_combobox, 5, 1, 1, 1)
        self.open_pushbutton = QtWidgets.QPushButton(self.setting)
        self.open_pushbutton.setEnabled(True)
        self.open_pushbutton.setObjectName("open_pushbutton")
        self.gridLayout.addWidget(self.open_pushbutton, 6, 1, 1, 1)
        self.clear_pushbutton = QtWidgets.QPushButton(self.setting)
        self.clear_pushbutton.setObjectName("clear_pushbutton")
        self.gridLayout.addWidget(self.clear_pushbutton, 7, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 8, 1, 1, 1)
        self.label_2.raise_()
        self.baudrate_combobox.raise_()
        self.label_4.raise_()
        self.parity_combobox.raise_()
        self.label_6.raise_()
        self.flowcontrol_combobox.raise_()
        self.label_3.raise_()
        self.databits_combobox.raise_()
        self.label_5.raise_()
        self.stopbits_combobox.raise_()
        self.device_combobox.raise_()
        self.label.raise_()
        self.device_combobox.raise_()
        self.open_pushbutton.raise_()
        self.clear_pushbutton.raise_()
        self.horizontalLayout_2.addWidget(self.setting)
        self.receive = QtWidgets.QGroupBox(self.centralwidget)
        self.receive.setObjectName("receive")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.receive)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rx_textbrowser = QtWidgets.QTextBrowser(self.receive)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.rx_textbrowser.setFont(font)
        self.rx_textbrowser.setObjectName("rx_textbrowser")
        self.horizontalLayout.addWidget(self.rx_textbrowser)
        self.horizontalLayout_2.addWidget(self.receive)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionScan = QtWidgets.QAction(MainWindow)
        self.actionScan.setObjectName("actionScan")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionScan)
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.databits_combobox.setCurrentIndex(3)
        self.clear_pushbutton.clicked.connect(self.rx_textbrowser.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CP2110 HID USB-to-UART"))
        self.setting.setTitle(_translate("MainWindow", "Setting"))
        self.label.setText(_translate("MainWindow", "Device List"))
        self.label_2.setText(_translate("MainWindow", "Baudrate"))
        self.baudrate_combobox.setItemText(0, _translate("MainWindow", "9600"))
        self.baudrate_combobox.setItemText(1, _translate("MainWindow", "38400"))
        self.baudrate_combobox.setItemText(2, _translate("MainWindow", "115200"))
        self.label_4.setText(_translate("MainWindow", "Parity"))
        self.parity_combobox.setItemText(0, _translate("MainWindow", "No Parity"))
        self.parity_combobox.setItemText(1, _translate("MainWindow", "Odd Parity"))
        self.parity_combobox.setItemText(2, _translate("MainWindow", "Even Parity"))
        self.parity_combobox.setItemText(3, _translate("MainWindow", "Mark Parity"))
        self.parity_combobox.setItemText(4, _translate("MainWindow", "Space Parity"))
        self.label_6.setText(_translate("MainWindow", "Flow Control"))
        self.flowcontrol_combobox.setItemText(0, _translate("MainWindow", "No Flow Control"))
        self.flowcontrol_combobox.setItemText(1, _translate("MainWindow", "HW Flow Control"))
        self.label_3.setText(_translate("MainWindow", "Data Bits"))
        self.databits_combobox.setItemText(0, _translate("MainWindow", "5"))
        self.databits_combobox.setItemText(1, _translate("MainWindow", "6"))
        self.databits_combobox.setItemText(2, _translate("MainWindow", "7"))
        self.databits_combobox.setItemText(3, _translate("MainWindow", "8"))
        self.label_5.setText(_translate("MainWindow", "Stop Bits"))
        self.stopbits_combobox.setItemText(0, _translate("MainWindow", "1"))
        self.stopbits_combobox.setItemText(1, _translate("MainWindow", "2"))
        self.open_pushbutton.setText(_translate("MainWindow", "Open"))
        self.clear_pushbutton.setText(_translate("MainWindow", "Clear"))
        self.receive.setTitle(_translate("MainWindow", "Receive"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionScan.setText(_translate("MainWindow", "Scan"))
        self.actionScan.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionAbout.setShortcut(_translate("MainWindow", "Ctrl+A"))

